# config.yaml
data:
  input_path: "data/documents"  # 文档存储目录
  file_pattern:                 # 文件匹配模式
    - "*.pdf"
    - "*.docx"
  output_db: "vector_stores/bdap_faiss_index"  # 向量库输出路径

processing:
  chunk_size: 600               # 文本块大小
  chunk_overlap: 120            # 文本块重叠量
  separators:                   # 文本分隔符
    - "\n\n"
    - "\n"
    - "。"
    - " "
    - ""

embedding:
  model_type: "huggingface"     # 嵌入模型类型 (huggingface/openai)
  model_name: "BAAI/bge-large-zh-v1.5"  # HuggingFace模型
  # openai_api_key: "sk-..."    # OpenAI密钥

metadata:
  default_title: "BDAP技术文档"
  source_field: "file_name"     # 使用文件名作为来源
#  extra_fields:                 # 额外元数据字段
