# config.yaml
data:
  input_path: "data/documents"  # 文档存储目录
  file_pattern:                 # 文件匹配模式
    - "*.pdf"
    - "*.docx"
  output_db: "vector_stores/bdap_faiss_index"  # 向量库输出路径

processing:
  chunk_size: 600               # 文本块大小
  chunk_overlap: 120            # 文本块重叠量
  separators:                   # 文本分隔符
    - "\n\n"
    - "\n"
    - "。"
    - " "
    - ""

embedding:
  model_type: "bge"
  model_name: "BAAI/bge-m3"
  model_path: "./models/BAAI/bge-m3"  # 如果你本地已经下载
  encode_kwargs:
    normalize_embeddings: true
  device: "cpu"  # 或者 cpu


metadata:
  default_title: "BDAP技术文档"
  source_field: "file_name"     # 使用文件名作为来源
#  extra_fields:                 # 额外元数据字段
